name: get_version
description: Get the Version Name, Version Code, Platform and OS Version, and
  App ID on iOS and Android.
version: 0.3.0
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/fluttercommunity/get_version
maintainer: Rody Davis (@rodydavis)

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^2.0.2

flutter:
  plugin:
    androidPackage: com.appleeducate.getversion
    pluginClass: GetVersionPlugin
